TP/CFlix/CFlix/CFlix/Models/ViewModels/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CFlix.Models.ViewModels
{
    public class ReviewViewModel
    {
        //[Required]
        //public int MediaId { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(4096)]
        public string Content { get; set; }
    }
}

TP/CFlix/CFlix/CFlix/Controllers/ProfileController.cs
using CFlix.Attributes;
using CFlix.Models;
using CFlix.Models.ViewModels;
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CFlix.Controllers
{
    [ChallengeStageFilter(2)]
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<CFlixUser> _userManager;
        private readonly IAchievementRepository _achievementRepository;

        public ProfileController(UserManager<CFlixUser> userManager,
            IAchievementRepository achievementRepository)
        {
            _userManager = userManager;
            _achievementRepository = achievementRepository;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(Index), new { profileName = "me" });
        }

        [Route("[controller]/{profileName}")]
        public async Task<IActionResult> Index(string profileName)
        {
            if (profileName == "me")
            {
                profileName = User.Identity.Name;
            }

            var user = await _userManager.FindByNameAsync(profileName);

            if (user == null)
            {
                return NotFound();
            }

            var ee = await _achievementRepository.GetEasterEggs(user.Id);
            return View(new ProfileStatViewModel(user, ee, user.UserName == User.Identity.Name));
        }

        [Route("[controller]/me/[action]")]
        public async Task<IActionResult> Edit()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(new ProfileViewModel(user));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("[controller]/me/[action]")]
        public async Task<IActionResult> Edit(ProfileViewModel profile)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userManager.GetUserAsync(User);
            user.UpdateWithProfileViewModel(profile);
            await _userManager.UpdateAsync(user);
            //// traitement de AccountType
            //var claims = await _userManager.GetClaimsAsync(user);
            //var roleClaim = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role);

            //if (Enum.TryParse(roleClaim.Value, out AccountType accountType) && profile.AccountType != accountType)
            //{
            //    await _userManager.ReplaceClaimAsync(user, roleClaim, new Claim(ClaimTypes.Role, profile.AccountType.ToString()));
            //}

            return RedirectToAction(nameof(Index), new { profileName = "me" });
        }
    }
}

TP/CFlix/CFlix/CFlix/Controllers/ReviewController.cs
using CFlix.Models;
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CFlix.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private readonly IMediaRepository _repo;
        private readonly UserManager<CFlixUser> _userManager;

        public ReviewController(
            UserManager<CFlixUser> userManager,
            IMediaRepository repository)
        {
            _userManager = userManager;
            _repo = repository;
        }

        [Route("[controller]/[action]/{reviewId}")]
        public async Task<IActionResult> ToggleHide(int reviewId, bool isHidden)
        {
            var review = await _repo.GetReviewAsync(reviewId);
            if (review == null || review.UserName != User.Identity.Name)
            {
                return NotFound();
            }

            review.IsHidden = !review.IsHidden;
            await _repo.EditReviewAsync(review);
            return RedirectToAction(nameof(MediaController.Detail), "Media", new { mediaId = review.MediaId });
        }
    }
}

TP/CFlix/CFlix/CFlix/Views/Shared/Components/Review/Default.cshtml
@using Microsoft.AspNetCore.Identity
@model CFlix.Models.ViewModels.ReviewViewModel
@inject UserManager<CFlixUser> UserManager

<div id="reviewSection" class="ui">
    <h3 class="ui horizontal divider header">
        <i class="comments outline icon"></i>
        Commentaires
    </h3>

    <div id="reviewForm">
        <form asp-route="Post_Review" method="post" class="ui inverted form">
            @*<input type="hidden" asp-for="MediaId" />*@
            <div class="disabled field">
                <textarea asp-for="Content"></textarea>
            </div>
            <button type="submit" class="ui fluid red labeled submit icon disabled button">
                <i class="icon edit"></i> Ajouter un commentaire
            </button>
        </form>
    </div>

    <div id="reviews" class="ui comments">
        @foreach (var review in (List<Review>)ViewBag.Reviews)
        {
            <div class="comment">
                <a class="avatar">
                    <img src="/images/avatar/@(review.User.AvatarType.ToString()).svg">
                </a>
                <div class="content">
                    <a class="author" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-profileName="@review.UserName">@review.User.DisplayName</a>
                    <div class="metadata">
                        <span class="date" data-comment-date="@DateTime.SpecifyKind(review.LastUpdated, DateTimeKind.Utc).ToString("o")"></span>
                    </div>
                    @if (review.IsHidden)
                    {
                        <div class="ui ignored info message">Ce commentaire a été masqué</div>
                    }
                    else
                    {
                        <div class="text">@Html.Raw(review.Content)</div>
                    }
                    <div class="actions">
                        @if (review.UserName == User.Identity.Name)
                        {
                            <a class="hide" asp-controller="Review" asp-action="ToggleHide" asp-route-reviewId="@review.Id" asp-route-isHidden="@review.IsHidden">
                                <i class="@(review.IsHidden? "unhide" : "hide") icon"></i>
                                @(review.IsHidden ? "Démasquer" : "Masquer")
                            </a>
                        }


                    </div>
                </div>
            </div>
        }
    </div>

</div>