TP/CFlix/CFlix/CFlix/Controllers/AchievementController.cs
using CFlix.Attributes;
using CFlix.Models;
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CFlix.Controllers
{
    [Authorize]
    [NeedToReadRules]
    public class AchievementController : Controller
    {
        private readonly IAchievementRepository _repo;
        private readonly UserManager<CFlixUser> _userManager;

        public AchievementController(IAchievementRepository repository,
            UserManager<CFlixUser> userManager)
        {
            _userManager = userManager;
            _repo = repository;
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Check(string easteregg)
        {
            await _repo.CheckEasterEgg((await _userManager.GetUserAsync(User)).Id, easteregg);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
        {
            var easterEggs = await _repo.GetEasterEggs((await _userManager.GetUserAsync(User)).Id);
            return View(easterEggs);
        }
        
        public async Task<IActionResult> Rate(int easterEggId, short value)
        {
            //User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value
            await _repo.RateEasterEggAsync((await _userManager.GetUserAsync(User)).Id, easterEggId, value);
            return RedirectToAction(nameof(Index));
        }
    }
}

TP/CFlix/CFlix/CFlix/ViewComponents/EasterEggViewComponent.cs
using CFlix.Models;
using CFlix.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CFlix.ViewComponents
{
    public class EasterEggViewComponent : ViewComponent
    {
        public EasterEggViewComponent()
        {
        }

        public IViewComponentResult Invoke(EasterEgg easterEgg, CFlixUserEasterEgg userEasterEgg)
        {
            if (userEasterEgg == null)
            {
                return View(easterEgg);
            }

            return View("Found", new EasterEggViewModel { EasterEgg = easterEgg, UserEasterEgg = userEasterEgg });
        }
    }
}

TP/CFlix/CFlix/CFlix/Views/Achievement/Index.cshtml
@model Dictionary<EasterEgg, CFlixUserEasterEgg>

@{
    ViewData["Title"] = "Easter Eggs";
}

<div class="ui segment inverted">
    <div class="ui header centered">
        Nous avons caché des easters eggs un peu partout sur le site, amusez-vous à tous les trouver ! :)<br />
        Dès que vous en aurez trouvé un saisissez-le ici pour le valider :
    </div>
    <div class="ui fluid vertical menu inverted">
        <form asp-area="" asp-controller="Achievement" asp-action="Check" method="post" class="item">
            <div class="ui right labeled action input">
                <span class="ui label">
                    Saississez votre easter egg
                </span>
                <input type="text" name="easteregg" placeholder="e.g. : CFl1X-17_5_v3rY_s1mp13">
                <button class="ui red icon button">
                    <i class="right arrow icon"></i>
                </button>
            </div>
            @if (ViewBag.DBError != null)
            {
                <div class="ui ignored error message">
                    @ViewBag.DBError
                </div>
            }
        </form>
    </div>
</div>

@{ var groups = Model.GroupBy(x => x.Key.EasterEggType); }

<div class="ui basic segment">
    <h1 class="ui horizontal divider blue header">
        <i class="trophy icon"></i>
        Easter Egg principaux
    </h1>
    <div class="ui basic segment">
        <div class="ui special six doubling centered cards">
            @foreach (var pair in groups.FirstOrDefault(x => x.Key == EasterEggType.Challenge).OrderBy(x => x.Key.Id))
            {
                <vc:easter-egg easter-egg="@pair.Key" user-easter-egg="@pair.Value"></vc:easter-egg>
            }
        </div>
    </div>

    <h1 class="ui horizontal divider blue header">
        <i class="diamond icon"></i>
        Easter Egg Bonus
    </h1>
    <div class="ui basic segment">
        <div class="ui special six doubling centered cards">
            @foreach (var pair in groups.FirstOrDefault(x => x.Key == EasterEggType.Bonus).OrderBy(x => x.Key.Id))
            {
                <vc:easter-egg easter-egg="@pair.Key" user-easter-egg="@pair.Value"></vc:easter-egg>
            }
        </div>
    </div>
</div>