TP/CFlix/CFlix/CFlix/Controllers/HomeController.cs
using CFlix.Attributes;
using CFlix.Data;
using CFlix.Models;
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading.Tasks;

namespace CFlix.Controllers
{
    [Authorize]
    [Route("/[action]")]
    public class HomeController : Controller
    {

        private readonly IMediaRepository _repo;
        private readonly CFlixROContext _context;

        public HomeController(IMediaRepository repository, CFlixROContext context)
        {
            _repo = repository;
            _context = context;
        }
        
        [Route("/")]
        [NeedToReadRules]
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAllMediasAsync());
        }

        [Route("", Name = "Get_Search")]
        [NeedToReadRules]
        public async Task<IActionResult> Search(string query)
        {
            try
            {
                var repo = new MediaRepository(_context);
                var results = await repo.SearchMediaAsync(query);
                ViewBag.Query = query;
                return View("Index", results);
            }
            catch (Exception ex) when (ex is InvalidCastException || ex is DbException)
            {
                ViewBag.DBError = ex.Message;
                return View("Index", new List<Media>());
            }
        }

        [Route("{statusCode?}")]
        public IActionResult Error(int statusCode)
        {
            statusCode = statusCode == 0 ? HttpContext.Response.StatusCode : statusCode;

            return View(statusCode);
        }
    }
}

TP/CFlix/CFlix/CFlix/Controllers/MediaController.cs
using CFlix.Attributes;
using CFlix.Models;
using CFlix.Models.ViewModels;
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CFlix.Controllers
{
    [Authorize]
    [NeedToReadRules]
    public class MediaController : Controller
    {
        private readonly IMediaRepository _repo;
        private readonly UserManager<CFlixUser> _userManager;

        public MediaController(
            UserManager<CFlixUser> userManager,
            IMediaRepository repository)
        {
            _userManager = userManager;
            _repo = repository;
        }

        [Route("[controller]/{mediaId}")]
        public async Task<IActionResult> Detail(int mediaId)
        {
            if ((await _repo.GetMediaWithDetailAsync(mediaId)) is Media m && m.IsAvailable)
            {
                return View(m);
            }

            return RedirectToAction("Home", "Index");
        }

        [Route("[controller]/{mediaId}/[action]", Name = "Post_Review")]
        [HttpPost]
        public async Task<IActionResult> Review(int mediaId, ReviewViewModel data)
        {
            return Forbid();

            var user = await _userManager.GetUserAsync(HttpContext.User);
            //HttpContext.User.Claims.FirstOrDefault(c => c.Type == "DisplayName").Value
            try
            {
                await _repo.AddReviewAsync(mediaId, user.UserName, data.Content);
            }
            catch (ArgumentException)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Detail), mediaId);
        }

    }
}

TP/CFlix/CFlix/CFlix/ViewComponents/NewsReleaseViewComponent.cs
using CFlix.Services.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CFlix.ViewComponents
{
    public class NewsReleaseViewComponent : ViewComponent
    {
        private readonly INewsReleaseRepository _repo;

        public NewsReleaseViewComponent(INewsReleaseRepository repo)
        {
            _repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var news = await _repo.GetNewsReleasesAsync();
            return View(news);
        }
    }
}

TP/CFlix/CFlix/CFlix/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "CFlix";
    ViewData["de-container"] = true;
}

@model IEnumerable<CFlix.Models.Media>

<div class="ui stackable internally celled grid">
    <div class="row">
        <div class="twelve wide column padded">
            <div class="ui fluid vertical menu">
                <form asp-route="Get_Search" method="get" class="item">
                    <div class="ui action input">
                        <input type="search" name="query" value="@ViewBag.Query" placeholder="Rechercher une série ou un film...">
                        <button class="ui red icon button">
                            <i class="search icon"></i>
                        </button>
                    </div>
                    @if (ViewBag.DBError != null)
                    {
                        <div class="ui ignored error message">
                            @ViewBag.DBError
                        </div>
                    }
                </form>
            </div>

            <div class="ui four doubling centered cards">
                @foreach (var media in Model)
                {
                    if (media.IsAvailable)
                    {
                        <a class="ui card" asp-area="" asp-controller="Media" asp-action="Detail" asp-route-mediaId="@media.Id">
                            <div class="ui image">
                                <img src="@media.ImageUri" alt="@media.Title" class="content" />
                            </div>
                        </a>
                    }
                    else
                    {
                        <div class="ui card">
                            <div class="ui disabled image">
                                <img src="@media.ImageUri" alt="@media.Title" class="content" />
                            </div>
                            <div class="extra content">
                                <span class="right floated">
                                    <span class="mediadate date" data-date="@DateTime.SpecifyKind(media.ReleaseDate, DateTimeKind.Utc).ToString("o")"></span>
                                    <i class="calendar icon"></i>
                                </span>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>

        <div class="four wide column">
            <vc:news-release></vc:news-release>
        </div>
    </div>
</div>